apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightyear-auth
  labels:
    app: lightyear-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightyear-auth
  template:
    metadata:
      labels:
        app: lightyear-auth
    spec:
      containers:
      - name: lightyear-auth
        image: julianv08/lightyear-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-firebase
              key: FIREBASE_API_KEY
        - name: FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: my-firebase
              key: FIREBASE_AUTH_DOMAIN
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: my-firebase
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: my-firebase
              key: FIREBASE_STORAGE_BUCKET
        - name: FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: my-firebase
              key: FIREBASE_MESSAGING_SENDER_ID
        - name: FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: my-firebase
              key: FIREBASE_APP_ID
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-db
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-db
              key: DB_PASS
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: my-db
              key: DB_HOST
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "100Mi"